apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "consumerapp.name" . }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  # Configuration values can be set as key-value properties
  ELASTIC_USERNAME: {{ .Values.configVars.ElasticUsername | quote }}
  ELASTIC_URL: {{ .Values.configVars.ElasticUrl | quote }}
  KAFKA_BROKER: {{ .Values.configVars.KafkaBroker | quote }}
  TOPIC_NAME: {{ .Values.configVars.TopicName | quote }}