apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.dockerConfigJson }}
kind: Secret
metadata:
  name: {{ .Values.imagePullSecretName }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson